# Project Euler: Problem 2
# Even Fibonacci Numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.
#
# Answer: 4,613,732

def evenFib():
    f = 1
    g = 1
    h = 1
    s = 0
    while h < 4000000:
        if h % 2 == 0:
            s += h
        h = f + g
        g = f
        f = h
    return s
